#!/usr/bin/env python

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']


helper.make_plugins( [
    'mu2e_RecoDataProducts',
    'mu2e_DataProducts',
    'mu2e_ConfigTools',
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Utilities',
    'art_root_io_TFileService',
    'art_root_io_tfile_support',
    'canvas',
    'fhiclcpp',
    'fhiclcpp_types',
    'cetlib',
    'cetlib_except',
    rootlibs,
    'xgboost',
    ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
